services:
    postgres:
        image: postgres:18-alpine
        container_name: storage
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            PGDATA: /var/lib/postgresql/data/pgdata
            TZ: Asia/Novosibirsk
            PGTZ: Asia/Novosibirsk
        ports:
            - "5432:5432"
        volumes:
            - ./storage/init:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgresql/data
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "10"
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app_network

    pgweb:
        image: sosedoff/pgweb:latest
        container_name: pgweb
        environment:
            PGWEB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
            TZ: Asia/Novosibirsk
        ports:
            - "8081:8081"
        depends_on:
            postgres:
                condition: service_healthy
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "10"
        restart: unless-stopped
        networks:
            - app_network

    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: $MINIO_ROOT_USER
            MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
            TZ: Asia/Novosibirsk
        volumes:
            - minio_data:/data
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "10"
        command: server /data --console-address ":9001"
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - app_network

    minio-init:
        image: minio/mc:latest
        environment:
            MINIO_ROOT_USER: $MINIO_ROOT_USER
            MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
            TZ: Asia/Novosibirsk
        depends_on:
            minio:
                condition: service_healthy
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "10"
        entrypoint: >
            /bin/sh -c "
            mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
            mc mb myminio/orders-attachments --ignore-existing;
            mc version enable myminio/orders-attachments;
            mc mb myminio/results --ignore-existing;
            mc version enable myminio/results;
            mc mb myminio/outgoing-attachments --ignore-existing;
            mc version enable myminio/outgoing-attachments;
            echo 'MinIO initialized successfully!';
            "
        networks:
            - app_network

    mail:
        build:
            context: ./mail
            dockerfile: Dockerfile
        container_name: mail
        environment:
            - YANDEX_REDIRECT_URI=${YANDEX_REDIRECT_URI}
            - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
            - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
            - YANDEX_TOKEN_URL=${YANDEX_TOKEN_URL}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            - MINIO_ENDPOINT=${MINIO_ENDPOINT}
            - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
            - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
            - MINIO_BUCKET=orders-attachments
            - MINIO_OUTGOING_BUCKET=outgoing-attachments
            - TZ=Asia/Novosibirsk
        depends_on:
            postgres:
                condition: service_healthy
            minio:
                condition: service_healthy
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "10"
        restart: unless-stopped
        networks:
            - app_network

    processors:
        build:
            context: ./processors
            dockerfile: Dockerfile
        container_name: processors
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            - MINIO_ENDPOINT=${MINIO_ENDPOINT}
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
            - TZ=Asia/Novosibirsk
        depends_on:
            postgres:
                condition: service_healthy
            minio:
                condition: service_healthy
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "10"
        restart: unless-stopped
        networks:
            - app_network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - "8000:8000"
        environment:
            - YANDEX_REDIRECT_URI=${YANDEX_REDIRECT_URI}
            - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
            - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
            - YANDEX_TOKEN_URL=${YANDEX_TOKEN_URL}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            - MINIO_ENDPOINT=${MINIO_ENDPOINT}
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
            - TZ=Asia/Novosibirsk
        depends_on:
            postgres:
                condition: service_healthy
            minio:
                condition: service_healthy
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "10"
        restart: unless-stopped
        networks:
            - app_network

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/certs:/etc/nginx/certs:ro
        depends_on:
            - frontend
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "10"
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
        name: app_network

volumes:
    minio_data:
    postgres_data:
